version = 0.1

[default.build.parameters]
debug = false
use_container = false

[default.deploy.parameters]
debug = false
stack_name = "sam-bedrock-kb-aurora-rag"
resolve_s3 = true
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
